ALTER TABLE order_service_items
    DROP CONSTRAINT fk_order;

ALTER TABLE order_service_items
    DROP CONSTRAINT fk_service_item;

CREATE TABLE master_services
(
    master_id  INTEGER NOT NULL,
    service_id BIGINT  NOT NULL,
    CONSTRAINT pk_master_services PRIMARY KEY (master_id, service_id)
);

ALTER TABLE service_item
    ADD active BOOLEAN;

ALTER TABLE service_item
    ADD category VARCHAR(255);

ALTER TABLE service_item
    ADD duration INTEGER;

ALTER TABLE service_item
    ADD image_url VARCHAR(255);

ALTER TABLE service_item
    ALTER COLUMN active SET NOT NULL;

ALTER TABLE orders
    ADD address VARCHAR(255);

ALTER TABLE orders
    ADD completed_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE orders
    ADD email VARCHAR(255);

ALTER TABLE orders
    ADD notes VARCHAR(255);

ALTER TABLE orders
    ADD phone VARCHAR(255);

ALTER TABLE orders
    ADD quantity INTEGER;

ALTER TABLE orders
    ADD scheduled_time TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE orders
    ADD service_id BIGINT;

ALTER TABLE orders
    ADD total_price INTEGER;

ALTER TABLE master
    ADD available BOOLEAN;

ALTER TABLE master
    ADD completed_orders INTEGER;

ALTER TABLE master
    ADD description VARCHAR(255);

ALTER TABLE master
    ADD experience INTEGER;

ALTER TABLE master
    ADD phone VARCHAR(255);

ALTER TABLE master
    ADD photo_url VARCHAR(255);

ALTER TABLE master
    ADD rating DOUBLE PRECISION;

ALTER TABLE master
    ADD specialization VARCHAR(255);

ALTER TABLE master
    ALTER COLUMN available SET NOT NULL;

ALTER TABLE orders
    ALTER COLUMN service_id SET NOT NULL;

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service_item (id);

ALTER TABLE master_services
    ADD CONSTRAINT fk_masser_on_master FOREIGN KEY (master_id) REFERENCES master (id);

ALTER TABLE master_services
    ADD CONSTRAINT fk_masser_on_service_item FOREIGN KEY (service_id) REFERENCES service_item (id);

DROP TABLE order_service_items CASCADE;

ALTER TABLE orders
    DROP COLUMN customer_phone;

ALTER TABLE orders
    DROP COLUMN id;

ALTER TABLE master
    DROP COLUMN phone_number;

ALTER TABLE orders
    ALTER COLUMN customer_name DROP NOT NULL;

ALTER TABLE service_item
    ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE orders
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE service_item
    DROP COLUMN id;

ALTER TABLE service_item
    DROP COLUMN price;

ALTER TABLE service_item
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE master
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE service_item
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE service_item
    ADD price INTEGER;

ALTER TABLE service_item
    ALTER COLUMN price DROP NOT NULL;

ALTER TABLE orders
    ALTER COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE orders
    ALTER COLUMN status DROP NOT NULL;