spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://localhost:5435/alma_postgres-1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1337

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    serialization:
      indent_output: true  # Красивый формат JSON
    time-zone: Asia/Almaty
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8081
  address: 0.0.0.0  # Позволяет принимать подключения со всех интерфейсов

file:
  upload-dir: uploads/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

