spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:alma}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
    kz.almacleaning: INFO
  file:
    name: /var/log/alma/application.log
    max-size: 10MB
    max-history: 30

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  tomcat:
    max-threads: 200
    min-spare-threads: 20

file:
  upload-dir: /var/alma/uploads/ 