spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/alma_postgres-1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD:1337}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    kz.almacleaning: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081
  address: 0.0.0.0

file:
  upload-dir: uploads/